name: Auto-translate Somali posts to English

on:
  push:
    branches:
      - main
    paths:
      - 'src/content/blog/**.md'

jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache Hugging Face models
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/huggingface
            ~/.cache/torch
          key: hf-${{ runner.os }}-${{ hashFiles('scripts/translate_local.py') }}

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install transformers[sentencepiece] pyyaml python-frontmatter torch --index-url https://download.pytorch.org/whl/cpu

      - name: Run local translation (no API keys)
        run: python scripts/translate_local.py

      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore(auto-translate): generate English versions for Somali posts"
            git push
          else
            echo "No changes to commit"
          fi


